name = "mamoochi"
pages_build_output_dir = "dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "mamootipagesdb"
database_id = "14a477f3-62e5-46c9-89b1-3cd621d28a45"
migrations_dir = "migrations"
